[phases.setup]
aptPkgs = ["tesseract-ocr", "tesseract-ocr-eng", "poppler-utils"]
nixPkgs = ["tesseract", "poppler_utils", "python3"]

[phases.install]
cmds = ["python3 -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]
